name: Docker Build and Push

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Ubuntu version to build'
        required: true
        default: '24.04'
        type: choice
        options:
          - '20.04'
          - '22.04'
          - '24.04'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      # 从模板生成 Dockerfile
      - name: Generate Dockerfile from template
        run: |
          mkdir -p build
          sed "s/{{UBUNTU_VERSION}}/${{ github.event.inputs.version }}/g" Dockerfile.template > build/Dockerfile
          echo "Generated Dockerfile:"
          cat build/Dockerfile
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./build
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-ssh:${{ github.event.inputs.version }}
