name: Docker Build and Push
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Ubuntu version to build (2004, 2204, 2404)'
        required: true
        default: '2404'
        type: choice
        options:
          - '2004'
          - '2204'
          - '2404'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract version info
        id: version_info
        run: |
          if [ "${{ github.event.inputs.version }}" == "2004" ]; then
            echo "tag=20.04" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.inputs.version }}" == "2204" ]; then
            echo "tag=22.04" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.inputs.version }}" == "2404" ]; then
            echo "tag=24.04" >> $GITHUB_OUTPUT
          fi
      
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./${{ github.event.inputs.version }}
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ubuntu-ssh:${{ steps.version_info.outputs.tag }}
